import Menu from "./components/OMC/Menu"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThirdwebProvider } from 'thirdweb/react';
import CssBaseline from '@mui/material/CssBaseline';
import Hero from './components/Hero';
import AppBar from "./components/AppBar";
import Theme from "./components/Theme";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>
      <body>
        <AppRouterCacheProvider>
          <Theme>
            <ThirdwebProvider>
              <CssBaseline />
              <AppBar menu={{
                desktop: <Menu mobile={false} />,
                mobile: <Menu mobile={true} />,
              }} />
              <Hero />
              {children}
            </ThirdwebProvider>
          </Theme>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
